exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - reprepro

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "pool"
    values:
      pool: true
  - scope:
      path: "dists"
    values:
      dists: true
